.PHONY: clean All

All:
	@echo "----------Building project:[ multiples-of-3-and-5 - Debug ]----------"
	@cd "multiples-of-3-and-5" && "$(MAKE)" -f  "multiples-of-3-and-5.mk"
clean:
	@echo "----------Cleaning project:[ multiples-of-3-and-5 - Debug ]----------"
	@cd "multiples-of-3-and-5" && "$(MAKE)" -f  "multiples-of-3-and-5.mk" clean
