.PHONY: clean All

All:
	@echo "----------Building project:[ Even-Fibonacci-numbers - Debug ]----------"
	@cd "Even-Fibonacci-numbers" && "$(MAKE)" -f  "Even-Fibonacci-numbers.mk"
clean:
	@echo "----------Cleaning project:[ Even-Fibonacci-numbers - Debug ]----------"
	@cd "Even-Fibonacci-numbers" && "$(MAKE)" -f  "Even-Fibonacci-numbers.mk" clean
