.PHONY: clean All

All:
	@echo "----------Building project:[ Check-if-Prime - Debug ]----------"
	@cd "Check-if-Prime" && "$(MAKE)" -f  "Check-if-Prime.mk"
clean:
	@echo "----------Cleaning project:[ Check-if-Prime - Debug ]----------"
	@cd "Check-if-Prime" && "$(MAKE)" -f  "Check-if-Prime.mk" clean
