#include <iostream>
#include <cinttypes>
/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 
 *       1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 * 
 */

int main(){
    std::cout << "Enter a value to find the sum of the even-valued terms\nbelow the entered number: ";
    
    int ans{2};
    int seq{0};
    int num1{1};
    int num2{2};
    int num3{0};
    std::cin >> seq;
    
    for (int i {3}; i < seq; i = num2){
        num3 = num2;
        num2 += num1;
        num1 = num3;
        if (num2 % 2 ==0)
           ans += num2;
        }

    std::cout << ans << std::endl;
    return 0;
}
